select sum(lo_extendedprice*lo_discount) as revenue from lineorder, dates where lo_orderdate = d_datekey and d_year = 1993 and lo_discount >= 1 and lo_discount <= 3 and lo_quantity < 25
select count(*) from lineorder, dates where lo_orderdate = d_datekey and d_year = 1993 and lo_discount >= 1 and lo_discount <= 3 and lo_quantity < 25
select sum(lo_extendedprice*lo_discount) as revenue from lineorder, dates where lo_orderdate = d_datekey and d_year = 1993 
select count(*) from lineorder, dates where lo_orderdate = d_datekey and d_year = 1993 
select sum(lo_revenue), d_year from lineorder, dates, part, supplier where lo_orderdate = d_datekey and lo_partkey = p_partkey and lo_suppkey = s_suppkey and p_brand = 'MFGR#2221' and s_region = 'ASIA' group by d_year order by d_year
select sum(lo_revenue) from lineorder, part where lo_partkey = p_partkey and p_brand = 'MFGR#2221'  
select avg(lo_revenue), d_year from lineorder, dates, part, supplier where lo_orderdate = d_datekey and lo_partkey = p_partkey and lo_suppkey = s_suppkey and p_brand = 'MFGR#2221' and s_region = 'ASIA' group by d_year order by d_year
select sum(lo_revenue), d_year from lineorder, dates, part, supplier where lo_orderdate = d_datekey and lo_partkey = p_partkey and lo_suppkey = s_suppkey and p_brand = 'MFGR#2221' and s_region = 'EUROPE' group by d_year, p_brand order by d_year, p_brand
select sum(lo_revenue) from lineorder, part, supplier where lo_partkey = p_partkey and lo_suppkey = s_suppkey and p_brand = 'MFGR#2221' and s_region = 'EUROPE' 
select count(*), d_year from lineorder, dates, part, supplier where lo_orderdate = d_datekey and lo_partkey = p_partkey and lo_suppkey = s_suppkey and p_brand = 'MFGR#2221' and s_region = 'EUROPE' group by d_year order by d_year
select c_nation, s_nation, d_year, sum(lo_revenue) as revenue from lineorder,customer,  supplier, dates where lo_custkey = c_custkey and lo_suppkey = s_suppkey and lo_orderdate = d_datekey and c_region = 'ASIA' and s_region = 'ASIA' and d_year >= 1992 and d_year <= 1997 group by c_nation, s_nation, d_year order by d_year asc, revenue desc
select s_nation, sum(lo_revenue) as revenue from lineorder, supplier where lo_suppkey = s_suppkey and s_region = 'ASIA' group by s_nation order by revenue desc
select s_nation, count(*) as revenue from lineorder, supplier where lo_suppkey = s_suppkey and s_region = 'ASIA' group by s_nation order by revenue desc
select s_nation, d_year, sum(lo_revenue) as revenue from lineorder, supplier, dates where lo_suppkey = s_suppkey and lo_orderdate = d_datekey and s_region = 'ASIA' and d_year >= 1992 and d_year <= 1997 group by s_nation, d_year order by d_year asc, revenue desc
select c_nation, s_nation, d_year, avg(lo_revenue) as avg_revenue from lineorder,customer,  supplier, dates where lo_custkey = c_custkey and lo_suppkey = s_suppkey and lo_orderdate = d_datekey and c_region = 'ASIA' and s_region = 'ASIA' and d_year >= 1992 and d_year <= 1997 group by c_nation, s_nation, d_year order by d_year asc, avg_revenue desc
select c_nation, s_nation, d_year, count(*) from lineorder,customer,  supplier, dates where lo_custkey = c_custkey and lo_suppkey = s_suppkey and lo_orderdate = d_datekey and c_region = 'ASIA' and s_region = 'ASIA' and d_year >= 1992 and d_year <= 1997 group by c_nation, s_nation, d_year order by d_year asc
select c_city, s_city, d_year, sum(lo_revenue) as revenue from lineorder,customer,  supplier, dates where lo_custkey = c_custkey and lo_suppkey = s_suppkey and lo_orderdate = d_datekey and c_nation = 'UNITED STATES' and s_nation = 'UNITED STATES' and d_year >= 1992 and d_year <= 1997 group by c_city, s_city, d_year order by d_year asc, revenue desc
select s_city, sum(lo_revenue) as revenue from lineorder, supplier where lo_suppkey = s_suppkey and s_nation = 'UNITED STATES' group by s_city order by revenue desc
select s_city, avg(lo_revenue) as avg_revenue from lineorder, supplier where lo_suppkey = s_suppkey and s_nation = 'UNITED STATES' group by s_city order by avg_revenue desc
select c_city, s_city, count(*) from lineorder,customer,  supplier where lo_custkey = c_custkey and lo_suppkey = s_suppkey and c_nation = 'UNITED STATES' and s_nation = 'UNITED STATES' group by c_city, s_city 
select c_city, s_city, d_year, avg(lo_revenue) as avg_revenue from  lineorder,customer, supplier, dates where lo_custkey = c_custkey and lo_suppkey = s_suppkey and lo_orderdate = d_datekey and c_nation = 'UNITED STATES' and s_nation = 'UNITED STATES' and d_year >= 1992 and d_year <= 1997 group by c_city, s_city, d_year order by d_year asc, avg_revenue desc 
select c_city, s_city, d_year, count(*) from lineorder,customer,  supplier, dates where lo_custkey = c_custkey and lo_suppkey = s_suppkey and lo_orderdate = d_datekey and c_nation = 'UNITED STATES' and s_nation = 'UNITED STATES' and d_year >= 1992 and d_year <= 1997 group by c_city, s_city, d_year order by d_year asc
select d_year, s_nation, p_category, sum(lo_revenue - lo_supplycost) as profit from lineorder,dates, customer, supplier, part  where lo_custkey = c_custkey and lo_suppkey = s_suppkey and lo_partkey = p_partkey and lo_orderdate = d_datekey and c_region = 'AMERICA' and s_region = 'AMERICA' and (d_year = 1997 or d_year = 1998) and (p_mfgr = 'MFGR#1' or p_mfgr = 'MFGR#2') group by d_year, s_nation, p_category order by d_year, s_nation, p_category
select d_year, s_nation, p_category, sum(lo_revenue - lo_supplycost) as profit from lineorder, dates, supplier, part  where lo_suppkey = s_suppkey and lo_partkey = p_partkey and lo_orderdate = d_datekey and s_region = 'AMERICA' and (d_year = 1997 or d_year = 1998) and (p_mfgr = 'MFGR#1' or p_mfgr = 'MFGR#2') group by d_year, s_nation, p_category order by d_year, s_nation, p_category
select d_year, s_nation, p_category, avg(lo_revenue - lo_supplycost) as avg_profit from lineorder, dates, customer, supplier, part   where lo_custkey = c_custkey and lo_suppkey = s_suppkey and lo_partkey = p_partkey and lo_orderdate = d_datekey and c_region = 'AMERICA' and s_region = 'AMERICA' and (d_year = 1997 or d_year = 1998) and (p_mfgr = 'MFGR#1' or p_mfgr = 'MFGR#2') group by d_year, s_nation, p_category order by d_year, s_nation, p_category
select d_year, s_nation, p_category, count(*) from lineorder, dates, customer, supplier, part  where lo_custkey = c_custkey and lo_suppkey = s_suppkey and lo_partkey = p_partkey and lo_orderdate = d_datekey and c_region = 'AMERICA' and s_region = 'AMERICA' and (d_year = 1997 or d_year = 1998) and (p_mfgr = 'MFGR#1' or p_mfgr = 'MFGR#2') group by d_year, s_nation, p_category order by d_year, s_nation, p_category
select d_year, s_nation, count(*) from  lineorder,dates, supplier  where lo_suppkey = s_suppkey and lo_orderdate = d_datekey and s_region = 'AMERICA' and (d_year = 1997 or d_year = 1998) group by d_year, s_nation order by d_year, s_nation
select s_nation, count(*) from lineorder,supplier   where lo_suppkey = s_suppkey and s_region = 'AMERICA' group by s_nation order by s_nation
select d_year, s_nation, sum(lo_revenue) as revenue from lineorder,dates, supplier   where lo_suppkey = s_suppkey and lo_orderdate = d_datekey and s_region = 'AMERICA' and (d_year = 1997 or d_year = 1998) group by d_year, s_nation order by d_year, s_nation
select sum(lo_revenue), p_brand from lineorder, part, supplier where lo_partkey = p_partkey and lo_suppkey = s_suppkey and p_brand = 'MFGR#2221' and s_region = 'ASIA' group by p_brand order by p_brand